apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fhnu
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-fhnu@sha256:9af54c22205fdd0eb93ef9454b18515b68887c3dc57071db0c13854093c21c22
        name: my-nodejs
        resources: {}
status: {}
